### ISSUE TITLE
[Net.SecurityProtocolType]::Tls13 Throws Error on Unsupported Systems

### ISSUE THREAD

**Issue by thigley986** [rhymeswithmogul/NinjaRMM-PowerShell#1]
The line `[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12, [Net.SecurityProtocolType]::Tls13` throws an error on systems that do not support TLS 1.3.

I suggest checking first to see if the system supports TLS 1.3 and, if not, only invoking:
`[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12`

**Comment by rhymeswithmogul** [comment]
Which version of PowerShell are you using? It works for me on PS7, but I'm going to correct this anyway.

**Comment by thigley986** [comment]
Powershell 5.1, Build 17763, Rev 1490 on Server 2019.

**Comment by rhymeswithmogul** [comment]
Thank you for the bug report.  I've fixed this by enabling TLS 1.2, then checking to see if TLS 1.3 is available before attempting to enable that.  I should have the new version up on the PowerShell Gallery soon.
