### ISSUE TITLE
Unable to create API key

### ISSUE THREAD

**Issue by dkattan** [rhymeswithmogul/NinjaRMM-PowerShell#2]
The option to create API keys appears to have been removed from NinjaRMM, and they are referring to API Keys as "Legacy".

Without a legacy key, is there any way for this module to work?

**Comment by rhymeswithmogul** [comment]
Sadly, no. If they've turned that off, then I’ll need to research and implement the v2 API.

**Comment by xasz** [comment]
Found any? I am trying to use the API v2 with some Powershell, but cannot get any OAUTH work. NinjaRMM could not provide any example for me until now. Anyone of u gotten any further?

**Comment by rhymeswithmogul** [comment]
I did not.  Since then, I've changed jobs, and I no longer have access to NinjaRMM.  I'm going to freeze this project unless another maintainer comes along.  I apologize.

**Comment by dkattan** [comment]
> I did not. Since then, I've changed jobs, and I no longer have access to NinjaRMM. I'm going to freeze this project unless another maintainer comes along. I apologize.

Hey @rhymeswithmogul  I'm happy to take it over. 

I made progress with OAuth2 yesterday @xasz 

Go into your Ninja instance and under Configuration -> Integrations -> API click Add

![image](https://user-images.githubusercontent.com/1424395/129343612-7ecc7380-af19-44b7-933f-bb8c1843cbee.png)

![image](https://user-images.githubusercontent.com/1424395/129343556-d2c68117-e363-494a-849e-92a0a54f9a99.png)

The following code will open your browser and bring you to a consent screen that you'll have to consent to once, and upon consent will redirect to the URL provided https://localhost:8080 in this case, and in the URL params you'll find the tokens you need to actually perform the API calls.

The next steps would be to store those tokens somewhere secure, most importantly the refresh_token, and have some code that periodically refreshes the refresh_token so you have access forever. I think I read the default refresh_token lifetime for Ninja is 30 days. 

The refresh_token itself isn't used to access the APIs, instead it can be traded for an access_token by posting to the /oauth/token endpoint. I haven't tried that yet, but I think it will be trivial.

```powershell
function New-HttpQueryString
{
    [CmdletBinding()]
    param 
    (
        [Parameter(Mandatory = $true)]
        [String]
        $Uri,

        [Parameter(Mandatory = $true)]
        [Hashtable]
        $QueryParameter
    )
    # Add System.Web
    Add-Type -AssemblyName System.Web
    
    # Create a http name value collection from an empty string
    $nvCollection = [System.Web.HttpUtility]::ParseQueryString([String]::Empty)
    
    foreach ($key in $QueryParameter.Keys)
    {
        $nvCollection.Add($key, $QueryParameter.$key)
    }
    
    # Build the uri
    $uriRequest = [System.UriBuilder]$uri
    $uriRequest.Query = $nvCollection.ToString()
    
    return $uriRequest.Uri.OriginalString
}

Function Authorize-NRMM
{
    Param ($applicationId,$secret,$redirectUrl, 
    [Parameter(Mandatory)]
    [ValidateSet("monitoring","management", "offline_access")]
    [string[]]$scopes)
    $RequestAccessTokenUri = "$($BaseUrl)/oauth/authorize" 
    $Params = @{response_type="code";client_id=$applicationId;client_secret=$Secret;}   
    #$RequestAccessTokenUri += "?response_type=code&client_id=$($applicationId)&client_secret=$($Secret)"
    if($redirectUrl)
    {
        $Params.redirect_uri = $redirectUrl
    }
    if($scopes)
    {
        $Params.scope = $scopes -join " "
    }
    $Uri = New-HttpQueryString -Uri $RequestAccessTokenUri -QueryParameter $Params
    $contentType = 'text/html'
    try
    {
        Start $Uri        
        return $Token    
    }
    catch { throw }
}

$AuthorizeResponse = Authorize-NRMM -applicationId $ClientId -secret $Secret -redirectUrl https://localhost:8080/ -scopes monitoring,offline_access
$AuthorizeResponse
return 
```

**Comment by dkattan** [comment]
Also, it appears they have brought back "Legacy API keys" in the UI so this issue can be closed:

![image](https://user-images.githubusercontent.com/1424395/129344462-e3c866e8-e208-44cb-ad61-7bd302c9ea1a.png)

**Comment by rhymeswithmogul** [comment]
@dkattan:  Message sent!  If you want to keep this project alive, I can't really do the NinjaRMM stuff anymore, but I'll gladly help you out with the PowerShell side of things.
